services:
    dockerhoster:
        container_name: dockerhoster
        hostname: dockerhoster
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - /etc/hosts:/tmp/hosts
        networks:
            caddy_default:
                aliases:
                    - docker.hoster
        image: bpawnzz/dockerhoster:v1
networks:
    caddy_default:
        external: true
        name: caddy_default
